=== agarram12/lenguaje_marcas_garcia_ramos/Unidad03/Práctica3_DTDyXSD_ÁlvaroGarcíaRamos/Ejercicio3/universidad.dtd
<!ELEMENT datos_universidad (alumnos,profesores,asignaturas)>
<!ELEMENT alumnos (alumno+)>
<!ELEMENT alumno (dni_pasaporte,pais_procendencia*,nombre,primer_apellido,segundo_apellido,fecha_nac,direccion,matriculado*,nota*)>
<!ELEMENT direccion (codpostal*,telefonos*,correo*)>
<!ELEMENT dni_pasaporte (#PCDATA)>
<!ELEMENT pais_procedencia (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT primer_apellido (#PCDATA)>
<!ELEMENT segundo_apellido (#PCDATA)>
<!ELEMENT fecha_nac (#PCDATA)>
<!ELEMENT codpostal (#PCDATA)>
<!ELEMENT telefonos (#PCDATA)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT matriculado (#PCDATA)>
<!ELEMENT nota (#PCDATA)>
<!ATTLIST nota asig CDATA #REQUIRED>
<!ELEMENT profesores (profesor+)>
<!ELEMENT profesor (dni_pasaporte,pais_procedencia*,nombre,primer_apellido,segundo_apellido,fecha_nac,direccion,despacho)>
<!ELEMENT despacho (#PCDATA)>
<!ELEMENT asignaturas (asignatura+)>
<!ELEMENT asignatura (codigo,creditos,carrera,curso)>
<!ATTLIST asignatura optativa ID #REQUIRED>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT creditos (#PCDATA)>
<!ELEMENT carrera (#PCDATA)>
<!ELEMENT curso (#PCDATA)>

=== agarram12/lenguaje_marcas_garcia_ramos/Unidad03/Práctica3_DTDyXSD_ÁlvaroGarcíaRamos/Ejercicio3/universidad.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE datos_universidad SYSTEM "./universidad.dtd">
<datos_universidad>
    <alumnos>
        <alumno>
            <dni_pasaporte>5432178P</dni_pasaporte>
            <nombre>Antonio</nombre>
            <primer_apellido>Ramos</primer_apellido>
            <segundo_apellido>Cortés</segundo_apellido>
            <fecha_nac>09/11/2000</fecha_nac>
            <direccion>
                <codpostal>11150</codpostal>
                <telefonos>678954321</telefonos>
                <correo>antonio@gmail.com</correo>
            </direccion>
            <matriculado>Matemáticas</matriculado>
            <matriculado>Historia</matriculado>
            <nota asig="Matemáticas">NT</nota>
            <nota asig="Historia">AP</nota>
        </alumno>
    </alumnos>
    <profesores>
        <profesor>
                <dni_pasaporte>46423454N</dni_pasaporte>
                <pais_procedencia>Alemania</pais_procedencia>
                <nombre>Ana</nombre>
                <primer_apellido>Fuch</primer_apellido>
                <segundo_apellido>Herrera</segundo_apellido>
                <fecha_nac>06/07/1998</fecha_nac>
                <direccion>
                    <codpostal>28440</codpostal>
                    <telefonos>678903211</telefonos>
                    <correo>ana@gmail.com</correo>
                </direccion>
                <despacho>BC-02</despacho>
        </profesor>
    </profesores>
    <asignaturas>
        <asignatura optativa="si">
                <codigo>1</codigo>
                <creditos>32</creditos>
                <carrera>IF</carrera>
                <curso>2</curso>
        </asignatura>
    </asignaturas>
</datos_universidad>
